"""added a new table called transactions 

Revision ID: 0dfb782ec2f8
Revises: 6a64f50b91f7
Create Date: 2026-08-20 19:48:01.959849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfb782ec2f8'
down_revision: Union[str, Sequence[str], None] = '6a64f50b91f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
