"""update the cost field in Transaction

Revision ID: 3e9f10aa9b94
Revises: f34b4de5a139
Create Date: 2026-08-20 20:45:37.435856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9f10aa9b94'
down_revision: Union[str, Sequence[str], None] = 'f34b4de5a139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
