"""add default currency to users and add some change in code

Revision ID: 4ac603ab7a42
Revises: a1773b51ba82
Create Date: 2026-08-19 18:51:23.721758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac603ab7a42'
down_revision: Union[str, Sequence[str], None] = 'a1773b51ba82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_currency', sa.String(length=50), server_default='USD', nullable=False))
    op.drop_column('users', 'defaultCurrency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('defaultCurrency', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'default_currency')
    # ### end Alembic commands ###
