"""addBoolean to user

Revision ID: 6a64f50b91f7
Revises: debf8b41b3ff
Create Date: 2026-08-19 19:28:37.577813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a64f50b91f7'
down_revision: Union[str, Sequence[str], None] = 'debf8b41b3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isSetupComplete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isSetupComplete')
    # ### end Alembic commands ###
