"""add default currency to users and add some change table title

Revision ID: debf8b41b3ff
Revises: 4ac603ab7a42
Create Date: 2026-08-19 18:59:20.414818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'debf8b41b3ff'
down_revision: Union[str, Sequence[str], None] = '4ac603ab7a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('defaultCurrency', sa.String(length=50), server_default='USD', nullable=False))
    op.drop_column('users', 'default_currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_currency', sa.VARCHAR(length=50), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('users', 'defaultCurrency')
    # ### end Alembic commands ###
